global:
  listen_port: 9271
  scrape_interval: 15s
  log_level: info

sensors:
  temperature:
    - name: example_1
      sensor_id: 00000da6f208
    - name: example_2
      sensor_id: 00000da6f209
  voltage:
    - name: test_vol
      bus: 1
